export function Technologies() {
  return (
    <div className="flex gap-2">
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/nodedotjs/5FA04E"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/typescript/3178C6"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/react/61DAFB"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/shadcnui/000000/ffffff"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/reacthookform/EC5990"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/reactquery/FF4154"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/reactrouter/CA4245"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/tailwindcss/06B6D4"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/zod/3E67B1"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/express/000000/ffffff"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/jsonwebtokens/000000/ffffff"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/mongodb/47A248"
      />
      <img
        height="32"
        width="32"
        src="https://cdn.simpleicons.org/mongoose/880000"
      />
    </div>
  );
}
